fixup a few more names

diff --git a/.github/workflows/ci-check-nix.yml b/.github/workflows/ci-check-nix.yml
--- a/.github/workflows/ci-check-nix.yml
+++ b/.github/workflows/ci-check-nix.yml
@@ -5,8 +5,7 @@ on:
   pull_request:
 
 jobs:
-  # WARNING: do not change this job name. It is a required status check for PRs to `main`.
-  nix-check:
+  run:
     strategy:
       matrix:
         cmakeBuildType: [debug, release]
@@ -34,3 +33,16 @@ jobs:
           authToken: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
       - name: Build and check install (${{ matrix.cmakeBuildType }})
         run: nix --print-build-logs build '.#checks.x86_64-linux.llzk-installcheck-${{ matrix.cmakeBuildType }}'
+
+  # WARNING: do not change this job name. It is a required status check for PRs to `main`.
+  nix-check-result:
+    needs: run
+    runs-on: ubuntu-24.04
+    if: ${{ !cancelled() }}
+    steps:
+      - name: Verify nix-check passed
+        run: |
+          if [[ "${{ needs.run.result }}" != "success" ]]; then
+            echo "nix-check failed or was cancelled"
+            exit 1
+          fi
